name: ${SERVER_NAME:-aether}

services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ${SERVER_NAME:-aether}
    container_name: tailscale-${SERVER_NAME:-aether}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:minecraft
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  neoforge:
    build:
      context: .
      args:
        NEOFORGE_VERSION: ${NEOFORGE_VERSION}
    image: aether:${NEOFORGE_VERSION}
    pull_policy: never
    env_file:
      - .env
    network_mode: service:tailscale
    depends_on:
      - tailscale
    volumes:
      - server-data:/server
    container_name: ${SERVER_NAME:-aether}
    environment:
      - JAVA_TOOL_OPTIONS=-Xms${JAVA_MIN_MEMORY:-4G} -Xmx${JAVA_MAX_MEMORY:-8G}
    stdin_open: true
    tty: true
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser-${SERVER_NAME:-aether}
    network_mode: service:tailscale
    depends_on:
      - tailscale
      - neoforge
    volumes:
      - server-data:/srv
    restart: unless-stopped

volumes:
  tailscale-data:
  server-data: