name: filebrowser

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - /home/${USER}/minecraft-servers:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped