services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    ports:
      - "8080:80"
    volumes:
      - ../servers:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
    restart: unless-stopped